name: Build Nx Angular App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Add a step to create the missing environment.prod.ts file
      - name: Create missing environment file
        run: |
          mkdir -p apps/baza-karm/src/env
          echo "export const environment = { production: true };" > apps/baza-karm/src/env/environment.prod.ts

      - name: Build Nx app
        run: npx nx run baza-karm:build:production
